coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
